# Generated by Django 2.2.7 on 2019-12-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detailusluga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название элемента до 100 символов', max_length=100, verbose_name='Название')),
                ('title', models.CharField(help_text='Title для SEO до 200 символов', max_length=200, verbose_name='Заголовок для SEO')),
                ('description', models.CharField(blank=True, help_text='Мета-описание для SEO до 450 символов: необязательно', max_length=450, verbose_name='Мета-описание')),
                ('slug', models.SlugField(help_text='писать только латинскими буквами, вместо пробела тире', max_length=250, unique=True, verbose_name='URL-адрес')),
                ('h1', models.CharField(blank=True, help_text='Заголовок h1 на странице', max_length=100, verbose_name='Заголовок на странице')),
                ('minitext', models.CharField(blank=True, help_text='Описание под заголовком до 300 символов', max_length=300, verbose_name='Небольшое описание')),
                ('bigimg', models.ImageField(blank=True, help_text='Изображение размером 1920x1024', upload_to='uslugi/', verbose_name='Загрузить большое изображение')),
                ('uslugaimg', models.ImageField(blank=True, help_text='Изображение размером 473x630', upload_to='uslugi/', verbose_name='Загрузить небольшое изображение')),
            ],
            options={
                'verbose_name': 'Услуга - отдельная страница',
                'verbose_name_plural': 'Услуги - отдельная страница',
            },
        ),
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='заголовок для поисковой оптимизации до 200 символов', max_length=200, verbose_name='Заголовок страницы: title')),
                ('description', models.CharField(blank=True, help_text='мета-описание страницы для поисковой оптимизации до 450 символов, необязательно', max_length=450, verbose_name='Описание страницы: description')),
                ('name', models.CharField(help_text='заголовок для отображения на сайте до 200 символов', max_length=200, verbose_name='Название страницы')),
                ('minidescription', models.CharField(blank=True, help_text='текстовое описание под заголовком страницы, до 200 символов', max_length=200, verbose_name='Текстовое описание')),
                ('uslugiimg', models.ImageField(blank=True, help_text='размер 1920x1024 в идеале, но если что изображение обрежется', upload_to='contact/', verbose_name='Изображение на странице')),
            ],
            options={
                'verbose_name': 'Услуга: общая информация на странице',
                'verbose_name_plural': 'Услуги: общая информация на странице',
            },
        ),
    ]
