# Generated by Django 2.2.7 on 2019-12-19 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0002_auto_20191205_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailusluga',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
