# Generated by Django 2.2.7 on 2019-12-19 22:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0003_detailusluga_date_pub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailusluga',
            options={'verbose_name': 'Английский - отдельная страница', 'verbose_name_plural': 'Английский - отдельная страница'},
        ),
        migrations.AlterModelOptions(
            name='uslugi',
            options={'verbose_name': 'Английский: общая информация на странице', 'verbose_name_plural': 'Английский: общая информация на странице'},
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Заголовок над документом до 150 символов', max_length=150, verbose_name='Заголовок документа')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Загрузить файл')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('materal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='uslugi.Detailusluga')),
            ],
            options={
                'verbose_name': 'Документы',
            },
        ),
    ]
