# Generated by Django 2.2.7 on 2019-12-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='заголовок для SEO до 200 символов', max_length=200, verbose_name='Title для SEO')),
                ('description', models.CharField(blank=True, help_text='Мета-описание для SEO, до 450 символов, необязательно', max_length=450)),
                ('h1', models.CharField(help_text='Заголовок на странице, обязателен', max_length=150, verbose_name='Заголовок на странице')),
                ('matimg', models.ImageField(help_text='изображение лучше брать вертикальное, обрежется до 960x1300', upload_to='materials/', verbose_name='Загрузить изображение для оформдения страницы')),
            ],
            options={
                'verbose_name': 'Страница материалов',
                'verbose_name_plural': 'Страницы материалов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Заголовок над документом до 150 символов', max_length=150, verbose_name='Заголовок документа')),
                ('materal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='materials.Materials')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='materials.Document')),
            ],
        ),
    ]
