# Generated by Django 2.2.7 on 2019-12-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Загрузить файл'),
        ),
    ]
