# Generated by Django 2.2.7 on 2019-11-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='заголовок для поисковой оптимизации до 200 символов', max_length=200, verbose_name='Заголовок страницы: title')),
                ('description', models.CharField(blank=True, help_text='мета-описание страницы для поисковой оптимизации до 450 символов, необязательно', max_length=450, verbose_name='Описание страницы: description')),
                ('name', models.CharField(help_text='заголовок для отображения на сайте до 200 символов', max_length=200, verbose_name='Название страницы')),
                ('minidescription', models.CharField(blank=True, help_text='текстовое описание под заголовком страницы, до 200 символов', max_length=200, verbose_name='Текстовое описание')),
                ('contactimg', models.ImageField(blank=True, help_text='размер 1920x1024 в идеале, но если что изображение обрежется', upload_to='contact/', verbose_name='Изображение на странице')),
                ('contacttitle', models.CharField(blank=True, help_text='до 100 символов', max_length=100, verbose_name='Мини заголовок')),
                ('contactdescription', models.CharField(blank=True, help_text='до 100 символов', max_length=100, verbose_name='Мини описание')),
                ('phonename', models.CharField(help_text='название до 60 символов', max_length=60, verbose_name='Название поля: телефон')),
                ('phone', models.CharField(blank=True, help_text='до 25 символов, необязательно', max_length=25, verbose_name='Номер телефона')),
                ('adressname', models.CharField(help_text='название до 60 символов', max_length=60, verbose_name='Название поля: адрес')),
                ('adress', models.CharField(blank=True, help_text='до 100 символов, необязательно', max_length=100, verbose_name='Адрес')),
                ('nameemail', models.CharField(help_text='название до 60 символов', max_length=60, verbose_name='Название поля: email')),
                ('email', models.EmailField(blank=True, help_text='формат eeee@eee.ru, необязательно', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Информация на странице контактов',
                'verbose_name_plural': 'Информация на странице контактов',
            },
        ),
    ]
