# Generated by Django 2.2.7 on 2019-12-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='просто название категории до 50 символов', max_length=50, verbose_name='Название элемента - категории')),
                ('title', models.CharField(db_index=True, help_text='SEO заголовок до 200 символов', max_length=200, verbose_name='Заголовок категории - Title')),
                ('description', models.CharField(blank=True, help_text='Мета-описание для SEO до 450 символов', max_length=450, verbose_name='Description категории')),
                ('slug', models.SlugField(help_text='использовать латинские символы и тире', max_length=250, unique=True, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.Categories', verbose_name='Категория'),
        ),
    ]
