# Generated by Django 2.2.7 on 2019-12-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191216_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widgetaboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название элемента виджета до 50 символов', max_length=50, verbose_name='Название виджета')),
                ('title_widget', models.CharField(help_text='Заголовок для отображения на сайте', max_length=20, verbose_name='Заголовок виджета')),
            ],
        ),
    ]
