# Generated by Django 2.2.7 on 2019-12-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prepodovatel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Someaboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Навание элемента до 100 символов', max_length=100, verbose_name='Имя элемента')),
                ('zagolovok', models.CharField(blank=True, help_text='можно использовать html-теги: <span>, <br />', max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, help_text='Описание под заголовком до 250 символов', max_length=250, verbose_name='Текстовое описание')),
                ('someimg', models.ImageField(help_text='изображение обрежется до 1920x1024px, поэтому лучше брать большое', upload_to='some/', verbose_name='Добавить изображение')),
                ('titleleft', models.CharField(blank=True, help_text='Текст слева до 15 символов', max_length=15, verbose_name='Текст слева')),
            ],
            options={
                'verbose_name': 'Блок: под блоком обо мне',
                'verbose_name_plural': 'Блоки: под блоком обо мне',
            },
        ),
    ]
