# Generated by Django 2.2.7 on 2019-12-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_someaboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='someaboutme',
            name='description',
            field=models.CharField(blank=True, help_text='Описание под заголовком до 250 символов', max_length=450, verbose_name='Текстовое описание'),
        ),
    ]
