# Generated by Django 2.2.7 on 2019-12-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191201_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название элемента до 100 символов', max_length=100, verbose_name='Имя элемента')),
                ('minizagolovok', models.CharField(blank=True, help_text='небольшой заголовок до 100 символов', max_length=100, verbose_name='Заголовок H3')),
                ('zagolovok', models.CharField(blank=True, help_text='Основной заголовок до 100 символов', max_length=100, verbose_name='Заголовок H2')),
                ('description', models.CharField(blank=True, help_text='текстовое описание до 450 символов', max_length=450, verbose_name='Текстовое описание')),
            ],
            options={
                'verbose_name': 'Блок резюме',
                'verbose_name_plural': 'Блоки резюме',
            },
        ),
        migrations.CreateModel(
            name='Resumeelement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название до 100 символов, обязательно к заполнению', max_length=100, verbose_name='Название')),
                ('title', models.CharField(help_text='Заголовок в левом блоке', max_length=100, verbose_name='Наименование этапа')),
                ('period', models.CharField(blank=True, help_text='писать в формате: 2010-2013 года', max_length=40, verbose_name='Период')),
                ('titleright', models.CharField(blank=True, help_text='заголовок до 100 символов', max_length=100, verbose_name='Заголовок в правом блоке')),
                ('description', models.TextField(blank=True, help_text='текстовое описание в блоке', verbose_name='Текстовый блок')),
                ('nomer', models.CharField(help_text='номер элемента в формате: 03.', max_length=10, verbose_name='Номер элемента')),
            ],
            options={
                'verbose_name': 'Элемент в резюме',
                'verbose_name_plural': 'Элементы в резюме',
            },
        ),
        migrations.AlterField(
            model_name='someaboutme',
            name='description',
            field=models.CharField(blank=True, help_text='Описание под заголовком до 450 символов', max_length=450, verbose_name='Текстовое описание'),
        ),
    ]
