# Generated by Django 2.2.7 on 2019-12-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191203_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urok',
            options={'verbose_name': 'Блок 7.0: Для напоминаний', 'verbose_name_plural': 'Блок 7.0: Для напоминаний'},
        ),
        migrations.AddField(
            model_name='itemurok',
            name='itemimg',
            field=models.ImageField(blank=True, help_text='лучше вертикальное изображение', null=True, upload_to='urok/', verbose_name='Загрузить изображение'),
        ),
    ]
