# Generated by Django 2.2.7 on 2019-12-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191204_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additionslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название элемента до 60 символов', max_length=60, verbose_name='Имя элемента - новых не добавлять')),
                ('geoname', models.CharField(help_text='Имя месторасположения - например: Москва', max_length=60, verbose_name='Имя места')),
                ('koordinata_1', models.CharField(help_text='формат написания: (55°45′07″)', max_length=50, verbose_name='Координата - 1')),
                ('koordinata_2', models.CharField(help_text='формат написания: (37°36′56″)', max_length=50, verbose_name='Координата - 2')),
                ('link_to_map', models.URLField(verbose_name='Ссылка на карту Google или Yandex')),
                ('anchor_1', models.CharField(blank=True, help_text='имя анкора: Начало', max_length=20, verbose_name='Анкор - Начало')),
                ('anchor_2', models.CharField(blank=True, help_text='имя анкора: Обо мне', max_length=20, verbose_name='Анкор - Обо мне')),
                ('anchor_3', models.CharField(blank=True, help_text='имя анкора: Resume', max_length=20, verbose_name='Анкор - Resume')),
                ('anchor_4', models.CharField(blank=True, help_text='имя анкора: Projects', max_length=20, verbose_name='Анкор - Projects')),
                ('anchor_5', models.CharField(blank=True, help_text='имя анкора: Clients', max_length=20, verbose_name='Анкор - Clients')),
            ],
            options={
                'verbose_name': 'Блок 1-1: Слайдер - Дополнение',
                'verbose_name_plural': 'Блок 1-1: Слайдер - Дополнения',
            },
        ),
        migrations.CreateModel(
            name='Counterelementy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='имя элемента до 20 символов', max_length=20, verbose_name='Название элемента')),
                ('counter_1', models.CharField(blank=True, help_text='Число до 5 символов', max_length=5, null=True, verbose_name='Счетчик - 1')),
                ('counter_name_1', models.CharField(blank=True, help_text='название до 20 символов', max_length=20, null=True, verbose_name='Названия для счетчика 1')),
                ('counter_2', models.CharField(blank=True, help_text='Число до 5 символов', max_length=5, null=True, verbose_name='Счетчик - 2')),
                ('counter_name_2', models.CharField(blank=True, help_text='название до 20 символов', max_length=20, null=True, verbose_name='Названия для счетчика 2')),
                ('counter_3', models.CharField(blank=True, help_text='Число до 5 символов', max_length=5, null=True, verbose_name='Счетчик - 3')),
                ('counter_name_3', models.CharField(blank=True, help_text='название до 20 символов', max_length=20, null=True, verbose_name='Названия для счетчика 3')),
                ('counter_4', models.CharField(blank=True, help_text='Число до 5 символов', max_length=5, null=True, verbose_name='Счетчик - 4')),
                ('counter_name_4', models.CharField(blank=True, help_text='название до 20 символов', max_length=20, null=True, verbose_name='Названия для счетчика 4')),
            ],
            options={
                'verbose_name': 'Блок 3-1: Счетчик',
                'verbose_name_plural': 'Блок 3-1: Счетчики',
            },
        ),
        migrations.CreateModel(
            name='Sociallink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название элемента до 30 символов', max_length=30, verbose_name='Название элемента')),
                ('linkvk', models.URLField(blank=True, help_text='ссылка на соцсеть ВК', verbose_name='Ссылка ВК')),
                ('linkfb', models.URLField(blank=True, help_text='ссылка на соцсеть FB', verbose_name='Ссылка FB')),
                ('linkinst', models.URLField(blank=True, help_text='ссылка на соцсеть Instagram', verbose_name='Ссылка Inst')),
                ('linktw', models.URLField(blank=True, help_text='ссылка на соцсеть Twitter', verbose_name='Ссылка Twitter')),
            ],
            options={
                'verbose_name': 'Ссылки на соцсети',
                'verbose_name_plural': 'Ссылки на соцсети',
            },
        ),
        migrations.CreateModel(
            name='Textblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название элемента до 50 символов', max_length=50, verbose_name='Название элемента')),
                ('zagolovok', models.CharField(blank=True, help_text='заголовок до 100 символов', max_length=100, null=True, verbose_name='Заголовок')),
                ('text_in_block', models.TextField(blank=True, help_text='текстовая область без ограничений', null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок 8: Текстовый блок внизу',
                'verbose_name_plural': 'Блок 8: Текстовый блок внизу',
            },
        ),
    ]
