# Generated by Django 2.2.7 on 2019-12-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191216_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seohome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название элемента до 50 символов', max_length=50, verbose_name='Название элемента')),
                ('title', models.CharField(blank=True, help_text='SEO заголовок на главную страницу до 200 символов', max_length=200, null=True, verbose_name='Title для SEO')),
                ('description', models.CharField(blank=True, help_text='Мета-описание для SEO до 450 символов', max_length=450, null=True, verbose_name='Description для главной страницы')),
            ],
            options={
                'verbose_name': 'Блок 9: SEO для главной страницы',
                'verbose_name_plural': 'Блок 9: SEO для главной страницы',
            },
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Ссылки на соцсети на всем сайте', 'verbose_name_plural': 'Ссылки на соцсети на всем сайте'},
        ),
    ]
