# Generated by Django 2.2.7 on 2019-12-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('german', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailgerman',
            options={'verbose_name': 'Немецкий - отдельная страница', 'verbose_name_plural': 'Немецкий - отдельная страница'},
        ),
        migrations.AlterModelOptions(
            name='german',
            options={'verbose_name': 'Немецкий: общая информация на странице', 'verbose_name_plural': 'Немецкий: общая информация на странице'},
        ),
    ]
